version: '2.2'
services:
  # DB layer
  redis:
    container_name: redis
    hostname: redis
    image: redis:bullseye
    ports:
    - "6379:6379"
    networks:
    - default-net
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  # helper for DB
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
    - "redis"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
    - default-net
networks:
  default-net: