# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine

# Copy app files
COPY frontend /app
# Set the working directory to /app inside the container
WORKDIR /app
# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci
# Build the app
RUN npm run build
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app

# TODO: replace with
# CMD [ "npx", "serve", "build" ]
# requires nginx or any other webserver
CMD ["npm", "start"]